### ISSUE TITLE
Suddenly getting errors

### ISSUE THREAD

**Issue by petertornstrand** [atech/deployhq#3]
Today I suddenly got this error trying to deploy one of my projects. As far as I know I haven't updates Ruby or anything else for that matter.

```
/Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.2/lib/deploy/cli.rb:99:in `deploy': undefined method `each_with_object' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.2/lib/deploy/cli.rb:53:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.2/bin/deployhq:5:in `<top (required)>'
	from /usr/local/bin/deployhq:23:in `load'
	from /usr/local/bin/deployhq:23:in `<main>'
```

**Comment by darkphnx** [comment]
Hi Peter, 

When was the last time you successfully queued a deployment with the CLI?

**Comment by darkphnx** [comment]
I've found the problem server-side. We'll get a fix sorted for this tomorrow

**Comment by darkphnx** [comment]
Fix was actually very easy. Done and a new version is published since I noticed a few things that needed tidying up while I was in the gem.
