### ISSUE TITLE
Error when running with -c flag

### ISSUE THREAD

**Issue by petertornstrand** [atech/deployhq#4]
deployhq -c
/Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/cli.rb:19:in `read': no implicit conversion of true into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/cli.rb:19:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/cli.rb:45:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/cli.rb:45:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/bin/deployhq:5:in `<top (required)>'
	from /usr/local/bin/deployhq:23:in `load'
	from /usr/local/bin/deployhq:23:in `<main>'

**Comment by darkphnx** [comment]
Hi Peter,

The `-c` flag is only supported in 2.0.0 or higher, please update the gem with `gem update deployhq` and let me know if you have any problems.

Thanks,
Dan
