### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by petertornstrand** [atech/deployhq#5]
Waiting for deployment capacity.../Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/request.rb:45:in `make': Not Found at https://xxx.deployhq.com/projects/xxx/deployments/b8326f0f-53dc-230c-fa16-fc46b6cebd00/logs/poll?status=pending (Deploy::Errors::CommunicationError)
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/deployment_status_poll.rb:27:in `poll'
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/deployment.rb:32:in `status_poll'
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/cli.rb:111:in `deploy'
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/lib/deploy/cli.rb:53:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/deployhq-1.3.3/bin/deployhq:5:in `<top (required)>'
	from /usr/local/bin/deployhq:23:in `load'
	from /usr/local/bin/deployhq:23:in `<main>'

**Comment by darkphnx** [comment]
Hi Peter,

Please try updating to v2.0.1 with `gem update deployhq` some server-side things changed and we had to push a new release.
